server:
  port: 8081


spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/microuserservice
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8085

#euraka confugrition (now on Github)
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
     ratingHotelBreaker:
       registerHealthIndicator: true
       eventConsumerBufferSize: 10
       failuerRateThreshold: 50
       minimumNumberOfCalls: 5
       automaticTransitionFromOpenToHalfOpenEnabled: true
       waitDurationInOpenState: 6s
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowSize: 10
       slidingWindowType: COUNT_BASED

