server:
  port: 8081


spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/microuserservice
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8085

#euraka confugrition (now on Github)
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
